// automatically generated by the FlatBuffers compiler, do not modify

package Examples;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Cusip extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Cusip __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long c1() { return (long)bb.getInt(bb_pos + 0) & 0xFFFFFFFFL; }
  public long c2() { return (long)bb.getInt(bb_pos + 4) & 0xFFFFFFFFL; }
  public long c3() { return (long)bb.getInt(bb_pos + 8) & 0xFFFFFFFFL; }

  public static int createCusip(FlatBufferBuilder builder, long c1, long c2, long c3) {
    builder.prep(4, 12);
    builder.putInt((int)c3);
    builder.putInt((int)c2);
    builder.putInt((int)c1);
    return builder.offset();
  }
}

