// automatically generated by the FlatBuffers compiler, do not modify

package Examples;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Position extends Table {
  public static Position getRootAsPosition(ByteBuffer _bb) { return getRootAsPosition(_bb, new Position()); }
  public static Position getRootAsPosition(ByteBuffer _bb, Position obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Position __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int qty() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public long accountId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createPosition(FlatBufferBuilder builder,
      int qty,
      int nameOffset,
      long accountId) {
    builder.startObject(3);
    Position.addAccountId(builder, accountId);
    Position.addName(builder, nameOffset);
    Position.addQty(builder, qty);
    return Position.endPosition(builder);
  }

  public static void startPosition(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addQty(FlatBufferBuilder builder, int qty) { builder.addInt(0, qty, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addAccountId(FlatBufferBuilder builder, long accountId) { builder.addLong(2, accountId, 0L); }
  public static int endPosition(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishPositionBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

