// automatically generated by the FlatBuffers compiler, do not modify

package Examples;

public final class Side {
  private Side() { }
  public static final byte Bid = 0;
  public static final byte Ask = 1;

  public static final String[] names = { "Bid", "Ask", };

  public static String name(int e) { return names[e]; }
}

