// automatically generated by the FlatBuffers compiler, do not modify

package Examples;

public final class PosSec {
  private PosSec() { }
  public static final byte NONE = 0;
  public static final byte Position = 1;
  public static final byte Security = 2;

  public static final String[] names = { "NONE", "Position", "Security", };

  public static String name(int e) { return names[e]; }
}

